# Site settings
title: Sun [Secret Diary]
description: > # this means to ignore newlines until "baseurl:"
  Secret Diary
#baseurl: "/blog/" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: sundiary
encoding: UTF-8
google_analytics: no

# Build settings
markdown: kramdown
#collections:
#  projects:
#    collections_dir: projects
#    output: true
